---
  # Versions
  FROGS_version: ""
  
  # Paths
  gvl_apps_home: "/mnt/gvl/apps"
  
  FROGS_path: "{{ gvl_apps_home }}/FROGS"

  #tool installation variables

  galaxy_tools_galaxy_instance_url: "http://localhost/galaxy/"

  # A list of yml files that list the tools to be installed. See `files/tool_list.yaml.sample`
  galaxy_tools_tool_list_files: [ "tool_list.yaml" ]

  # should the playbook continue when errors are found
  galaxy_tools_ignore_errors: true

  # A system path from where this role will be run
  galaxy_tools_base_dir: /mnt/galaxy/tmp

  # Blank variable to make sure it's defined
  galaxy_tools_api_key: ''

  # A user for the Galaxy bootstrap user
  tools_admin_email: frogs@local.localhost
  tools_admin_username: frogs
  tools_admin_password: frogs01
  
  galaxy_server_dir: /mnt/galaxy/galaxy-app

  # A system path where a virtualend for Galaxy is installed
  galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"

  # A system path for Galaxy's main configuration file
  galaxy_config_file: "{{ galaxy_server_dir }}/config/galaxy.ini"

  #The linuxbrew paths
  gvl_tmp_path: "/mnt/gvl/tmp"

  microgvl_homebrew_temp: "{{ gvl_tmp_path }}/homebrew_temp"
  microgvl_homebrew_cache: "{{ gvl_tmp_path }}/homebrew_cache"
  homebrew_home: "/home/linuxbrew"
  homebrew_path: "{{ homebrew_home }}/.linuxbrew"
  
  #linuxbrew environment dictionary
  linuxbrew_env:
      LD_LIBRARY_PATH: ""
      PATH: "{{ homebrew_path }}/bin:{{ homebrew_path }}/sbin:{{ ansible_env.PATH }}"
      MANPATH: "{{ homebrew_path }}/share/man"
      INFOPATH: "{{ homebrew_path }}/share/info"
      HOMEBREW_TEMP: "{{ microgvl_homebrew_temp }}"
      HOMEBREW_CACHE: "{{ microgvl_homebrew_cache }}"
      TEMPDIR: "{{ gvl_tmp_path }}"
      TEMP: "{{ gvl_tmp_path}}"

...
